version: '3.8'

services:
  redis:
    image: redis:latest    
    container_name: my_redis  
    ports:
      - "6379:6379"
    networks:
      - app-network   
    volumes:
      - redis-data:/data  

  app:
    build:
      context: .  
    container_name: node-app  
    ports:
      - "3000:3000" 
    networks:
      - app-network  
    environment:
      REDIS_HOST: my_redis 

networks:
  app-network:
    driver: bridge  

volumes:
  redis-data:
    driver: local   
